package com.mayank.fooddelivery.exceptions;

public enum ExceptionType {
    RESTAURANT_ALREADY_EXISTS,
    RESTAURANT_NOT_FOUND,
    MENU_NOT_FOUND,
    MENU_ALREADY_EXISTS,
    CART_IS_EMPTY,
    MENU_ITEM_NOT_FOUND,
    ORDER_NOT_VALID,
    ORDER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    PAYMENT_NOT_EXISTS,
    DELIVERY_ALREADY_EXISTS,
    DELIVERY_NOT_FOUND,
    ORDER_NOT_CONFIRMED
}
